config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  resources :users
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'comments/create'

  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  resources :favorites, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  
  resources :posts
  
  
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  remember_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
    attr_accessor :remember_token
    mount_uploader :picture, PictureUploader
    has_many :posts, dependent: :destroy ,foreign_key: 'user'
    
    before_save { email.downcase! }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    
    # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

# ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

# 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

# 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    
  end

  def new
    @user = User.new
  end
  
  def create
    
    @user = User.new(user_params)   
    if @user.save
      log_in @user
      flash[:success] = "Tsukutta!へようこそ"
      redirect_to @user
    else
      flash[:error_messages] = @user.errors.full_messages
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  
  def update
    @user = User.find(params[:id])
   if @user.update_attributes(user_params)
    flash[:success] = "プロフィールが更新されました！"
    redirect_to @user
   else
      render'edit'
   end  
  end
  
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>プロフィールの更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "base" , :media => "all" %>

<% provide(:title, 'Sign up') %>
<h1>無料会員登録</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウントを作成する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "index" , :media => "all" %>


<%= link_to '投稿', new_post_path, class: "btn btn-outline-info" %>
<br></br>
<div class="recipe_content_wrapper">




    <div class="recipe_list_wrapper">
    <% if @user.posts.any? %>
        <% @user.posts.each do |post| %>
            <div class="recipe_list">
                    <div class="content-left">
                    <div class="post.picture"><%= image_tag post.picture.to_s  %></div>
                </div>
                <div class="content-center">
                    <p class="post.title"><%= post.title %></p>
                </div>
                <div class="btn btn-outline-info"><%= link_to "コメントする" , post  %></div>
                <div class="btn btn-outline-info"><%= link_to "削除" , post , method: :delete, data: {confirm: "投稿記事を削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %></div>
                    
                <div class="content-right">
                    <p class="post.user"><%=  link_to post.user.name, post.user %></p>
                    <p class="post.time"><%= post.created_at.to_s(:datetime_base) %></p>
                </div>
                </div>
    <% end %>
    <% else %>
      <div class="new-message">
        <p>まだ投稿がありません。</p>
        <p>作ったごはんについて投稿しましょう！</p>
      </div>
    <% end %>
    </div>
</div>


        